import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * `adapt` — generate thin per-tool adapter files (Layer 4).
 *
 * Most AI coding tools read AGENTS.md natively (Antigravity since v1.20.3,
 * Codex, Cursor, Copilot, and others), so adapters do not duplicate content:
 * they are generated pointers to AGENTS.md — the single canonical source —
 * for tools that use their own file name or support tool-specific overrides.
 *
 * Files carry a generation marker; adapt only overwrites files it generated
 * itself and refuses to touch hand-edited ones.
 */

export const GENERATION_MARKER = "Generated by `aigentdocs adapt` — edit AGENTS.md instead; this file is regenerated.";

export interface AdapterTarget {
  /** File to generate, relative to the repository root. */
  file: string;
  description: string;
  content: string;
}

const marker = (commentOpen: string, commentClose: string): string =>
  `${commentOpen} ${GENERATION_MARKER} ${commentClose}`;

export const ADAPTER_TARGETS: Record<string, AdapterTarget> = {
  claude: {
    file: "CLAUDE.md",
    description: "Claude Code entry file (imports AGENTS.md)",
    content: `${marker("<!--", "-->")}

@AGENTS.md
`,
  },
  cursor: {
    file: ".cursor/rules/aigentdocs.mdc",
    description: "Cursor project rule pointing to AGENTS.md",
    content: `---
description: AIGentDocs project instructions
alwaysApply: true
---

${marker("<!--", "-->")}

Follow the AI agent instructions in \`AGENTS.md\` at the repository root.
The project documentation under \`docs/project/\` is the source of truth;
start from \`docs/standard/AGENT.md\`.
`,
  },
  copilot: {
    file: ".github/copilot-instructions.md",
    description: "GitHub Copilot instructions pointing to AGENTS.md",
    content: `${marker("<!--", "-->")}

Follow the AI agent instructions in \`AGENTS.md\` at the repository root.
The project documentation under \`docs/project/\` is the source of truth;
start from \`docs/standard/AGENT.md\`.
`,
  },
  antigravity: {
    file: "GEMINI.md",
    description: "Antigravity-specific overrides (Antigravity reads AGENTS.md natively)",
    content: `${marker("<!--", "-->")}

<!-- Antigravity (CLI, IDE, and agent tooling) reads AGENTS.md natively, and
     this file takes priority over it for Antigravity-specific behavior.
     Keep it empty of duplicated rules: add only Antigravity-specific
     overrides below. -->

Follow the AI agent instructions in \`AGENTS.md\` at the repository root.
`,
  },
};

export interface AdaptResult {
  written: Array<{ file: string; description: string }>;
  skipped: Array<{ file: string; reason: string }>;
}

const exists = (p: string): Promise<boolean> => access(p).then(() => true, () => false);

/** Generate adapter files for the given tools (default: all registered). */
export async function adaptProject(targetDir: string, tools?: string[]): Promise<AdaptResult> {
  const requested = tools === undefined || tools.length === 0 ? Object.keys(ADAPTER_TARGETS) : tools;
  for (const tool of requested) {
    if (!(tool in ADAPTER_TARGETS)) {
      throw new Error(`unknown tool '${tool}' (available: ${Object.keys(ADAPTER_TARGETS).join(", ")})`);
    }
  }
  if (!(await exists(path.join(targetDir, "AGENTS.md")))) {
    throw new Error(`'AGENTS.md' not found in '${targetDir}' — adapters point to it. Run 'aigentdocs init' first.`);
  }

  const result: AdaptResult = { written: [], skipped: [] };
  for (const tool of requested) {
    const target = ADAPTER_TARGETS[tool];
    if (target === undefined) {
      continue;
    }
    const filePath = path.join(targetDir, target.file);
    if (await exists(filePath)) {
      const current = await readFile(filePath, "utf8");
      if (!current.includes(GENERATION_MARKER)) {
        result.skipped.push({ file: target.file, reason: "exists and was not generated by adapt — left untouched" });
        continue;
      }
    }
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, target.content);
    result.written.push({ file: target.file, description: target.description });
  }
  return result;
}
